---
# tasks file for /home/ec2-user/ansible/roles/apache

- name: installing apache
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: index.html
  ansible.builtin.copy:
    content: "<h1>Hello Clarusway</h1>"
    dest: /var/www/html/index.html

- name: restart apache2
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: yes