apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: nginx-server
  labels:
    environment: dev 
spec:
  selector:
    matchLabels:
      app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: mynginx
            image: nginx
            ports:
            - containerPort: 80