apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: todoapp
    spec:
      containers:
      - name: myweb
        imagePullPolicy: Always
        image: clarusway/todo
        ports:
        - containerPort: 3000
        env:
          - name: "DBHOST"
            value: mongodb-service
        resources: 
          limits: 
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 250Mi
            cpu: 80m