apiVersion: v1
kind: Pod
metadata:
  name: nginx-pd
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:1.19
    name: mynginx
    volumeMounts:
    - mountPath: /test
      name: emptydir-test
    ports:
    - containerPort: 80
  volumes:
  - name: emptydir-test
    emptyDir: {}
    