---
- name: Apache installation for webservers
  hosts: webservers
  become: yes
  tasks: 
   - name: install the latest version of Apache
     ansible.builtin.yum:
       name: httpd
       state: latest

   - name: start Apache
     ansible.builtin.shell: "service httpd start"

- name: Apache installation for ubuntuservers
  hosts: ubuntuservers
  become: yes
  tasks:
   - name: update
     ansible.builtin.shell: "apt update -y"

   - name: isntall the latest version of Apache
     ansible.builtin.apt:
       name: apache2
       state: latest
---