plugin: aws_ec2
regions:
  - "us-east-1"
keyed_groups: 
  - key: tags.Name
  - key: tags.environment
  - prefix: merhaba
filters:
  tag:environment: dev
compose:
  ansible_host: public_ip_address
# abc: private_ip_address           vpc de kullanilir.
