apiVersion: v1
kind: Secret 
metadata:
  name: mysecret
type: Opaque
data:    # burda stringData yazarsam base64 yerine normal isimleri yazabiliriz. admin ve passwordun kendisini
  username: YWRtaW4=
  password: MWYycDQu







  

#############################################################################

# methods

# 1. kubectl create secret generic db-user-pass --from-file=./username.txt --from-file=./password.txt

# 2. kubectl create secret generic db-user-pass-key --from-file=username=./username.txt --from-file=password=./password.txt

###########################################################################
# Encode

# echo -n "admin" | base64     
# base64 username.txt

# Decode

# echo "base64hali" | base64 --decode
# base64 username.txt --decode

############################################################################

# Create files needed for the rest of the example.
# echo -n 'admin' > ./username.txt
# echo -n '1f2d1e2e67df' > ./password.txt